"""
Biological Firewall Engine — PDF Security Report Generator.

Generates a professional, dark-themed A4 security report summarising
scan results and model statistics.  Uses only the fpdf2 library.

Usage:
    from report_generator import generate_security_report

    path = generate_security_report(scan_results, model_stats)
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Dict, List

from fpdf import FPDF


# ── colour palette ───────────────────────────────────────────────────
_CLR_HEADER_BG = (30, 30, 30)          # near-black header background
_CLR_HEADER_FG = (255, 255, 255)       # white header text
_CLR_ACCENT    = (0, 180, 140)         # teal accent for lines / titles
_CLR_ROW_EVEN  = (245, 245, 245)       # light grey alternating row
_CLR_ROW_ODD   = (255, 255, 255)       # white alternating row
_CLR_TEXT      = (30, 30, 30)          # default body text
_CLR_SUBTLE    = (120, 120, 120)       # muted / subtitle text
_CLR_BLOCKED   = (220, 50, 50)         # red for BLOCKED
_CLR_ALLOWED   = (0, 160, 80)         # green for ALLOWED


class _ReportPDF(FPDF):
    """Subclass of FPDF with custom header / footer for the report."""

    def header(self):
        """Minimal header — content is drawn manually in the body."""

    def footer(self):
        """Page footer with branding and page number."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_CLR_SUBTLE)
        self.cell(
            0,
            10,
            "Generated by Biological Firewall Engine v3.1 "
            "-- Powered by Drosophila Connectome"
            f"    |    Page {self.page_no()}/{{nb}}",
            align="C",
        )


# ── internal helpers ─────────────────────────────────────────────────

def _draw_title_block(pdf: _ReportPDF) -> None:
    """Draw the report header: title, subtitle, horizontal rule."""
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*_CLR_HEADER_BG)
    pdf.cell(0, 12, "Biological Firewall Engine", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*_CLR_ACCENT)
    pdf.cell(0, 10, "Security Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_CLR_SUBTLE)
    now = datetime.now().strftime("%Y-%m-%d  %H:%M:%S")
    pdf.cell(0, 6, f"Generated: {now}", new_x="LMARGIN", new_y="NEXT")

    # horizontal rule
    pdf.ln(4)
    y = pdf.get_y()
    pdf.set_draw_color(*_CLR_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(6)


def _section_heading(pdf: _ReportPDF, title: str) -> None:
    """Draw a dark section heading bar."""
    pdf.set_fill_color(*_CLR_HEADER_BG)
    pdf.set_text_color(*_CLR_HEADER_FG)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 9, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_text_color(*_CLR_TEXT)


def _kv_line(pdf: _ReportPDF, key: str, value: str) -> None:
    """Print a key: value line in the body."""
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(55, 6, f"  {key}:", new_x="END")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")


def _draw_executive_summary(
    pdf: _ReportPDF, scan_results: List[Dict]
) -> None:
    """Executive Summary section with counts and threat breakdown."""
    _section_heading(pdf, "Executive Summary")

    total = len(scan_results)
    threats = [r for r in scan_results if r.get("classification", "").lower() != "normal"]
    threat_count = len(threats)

    _kv_line(pdf, "Total Packets Scanned", f"{total:,}")
    _kv_line(pdf, "Threats Detected", f"{threat_count:,}")
    pdf.ln(2)

    # Breakdown by class
    classes = ["Normal", "DoS", "Probe", "R2L", "U2R"]
    counts = {}
    for cls in classes:
        counts[cls] = sum(
            1 for r in scan_results
            if r.get("classification", "").lower() == cls.lower()
        )

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(55, 6, "  Threat Breakdown:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for cls in classes:
        pdf.cell(60, 6, f"      {cls}", new_x="END")
        pdf.cell(0, 6, f"{counts[cls]:,}", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)


def _draw_model_info(pdf: _ReportPDF, model_stats: Dict) -> None:
    """Model Information section."""
    _section_heading(pdf, "Model Information")

    _kv_line(pdf, "Neurons", f"{model_stats.get('num_neurons', 'N/A'):,}")
    _kv_line(pdf, "Synapses", f"{model_stats.get('num_synapses', 'N/A'):,}")
    _kv_line(
        pdf,
        "Accuracy",
        f"{model_stats.get('accuracy', 0) * 100:.2f}%",
    )
    _kv_line(
        pdf,
        "F1 Score (macro)",
        f"{model_stats.get('f1_macro', 0):.4f}",
    )
    pdf.ln(4)


def _draw_threat_table(pdf: _ReportPDF, scan_results: List[Dict]) -> None:
    """Threat Log Table with alternating row colours."""
    _section_heading(pdf, "Threat Log")

    # Column definitions: (header_label, width, data_key, align)
    columns = [
        ("#",              10, "id",              "C"),
        ("Protocol",       22, "protocol_type",   "C"),
        ("Service",        28, "service",         "C"),
        ("Flag",           18, "flag",            "C"),
        ("Bytes",          22, "src_bytes",       "R"),
        ("Classification", 32, "classification",  "C"),
        ("Confidence",     28, "confidence",      "C"),
        ("Status",         30, "status",          "C"),
    ]

    row_h = 7

    # ── table header ─────────────────────────────────────────────────
    pdf.set_fill_color(*_CLR_HEADER_BG)
    pdf.set_text_color(*_CLR_HEADER_FG)
    pdf.set_font("Helvetica", "B", 8)
    for label, w, _, align in columns:
        pdf.cell(w, row_h, label, border=0, fill=True, align=align, new_x="END")
    pdf.ln(row_h)

    # ── table rows ───────────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 8)

    for idx, row in enumerate(scan_results):
        # Check for page break — leave room for footer
        if pdf.get_y() + row_h > pdf.h - 20:
            pdf.add_page()
            # Re-draw table header on new page
            pdf.set_fill_color(*_CLR_HEADER_BG)
            pdf.set_text_color(*_CLR_HEADER_FG)
            pdf.set_font("Helvetica", "B", 8)
            for label, w, _, align in columns:
                pdf.cell(w, row_h, label, border=0, fill=True, align=align, new_x="END")
            pdf.ln(row_h)
            pdf.set_font("Helvetica", "", 8)

        # Alternating row background
        bg = _CLR_ROW_EVEN if idx % 2 == 0 else _CLR_ROW_ODD
        pdf.set_fill_color(*bg)

        for label, w, key, align in columns:
            value = row.get(key, "")

            # Special formatting for status column
            if key == "status":
                status_str = str(value).upper()
                if status_str == "BLOCKED":
                    pdf.set_text_color(*_CLR_BLOCKED)
                else:
                    pdf.set_text_color(*_CLR_ALLOWED)
                pdf.set_font("Helvetica", "B", 8)
                pdf.cell(w, row_h, status_str, border=0, fill=True, align=align, new_x="END")
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_CLR_TEXT)
            elif key == "confidence":
                pdf.set_text_color(*_CLR_TEXT)
                pdf.cell(
                    w, row_h,
                    f"{float(value) * 100:.1f}%" if value != "" else "",
                    border=0, fill=True, align=align, new_x="END",
                )
            elif key == "src_bytes":
                pdf.set_text_color(*_CLR_TEXT)
                pdf.cell(
                    w, row_h,
                    f"{int(value):,}" if value != "" else "",
                    border=0, fill=True, align=align, new_x="END",
                )
            else:
                pdf.set_text_color(*_CLR_TEXT)
                pdf.cell(w, row_h, str(value), border=0, fill=True, align=align, new_x="END")

        pdf.ln(row_h)

    pdf.ln(4)


# ── public API ───────────────────────────────────────────────────────

def generate_security_report(
    scan_results: list,
    model_stats: dict,
    output_path: str = "security_report.pdf",
) -> str:
    """Generate a styled PDF security report and return its absolute path.

    Parameters
    ----------
    scan_results : list[dict]
        Each dict must contain the keys:
        ``id``, ``protocol_type``, ``service``, ``flag``,
        ``src_bytes``, ``classification``, ``confidence``, ``status``.
    model_stats : dict
        Must contain:
        ``num_neurons``, ``num_synapses``, ``accuracy``, ``f1_macro``.
    output_path : str, optional
        Destination file path for the generated PDF.
        Defaults to ``'security_report.pdf'`` in the current directory.

    Returns
    -------
    str
        Absolute path to the generated PDF file.
    """
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    _draw_title_block(pdf)
    _draw_executive_summary(pdf, scan_results)
    _draw_model_info(pdf, model_stats)
    _draw_threat_table(pdf, scan_results)

    pdf.output(output_path)

    return os.path.abspath(output_path)


# ── standalone demo ──────────────────────────────────────────────────

if __name__ == "__main__":
    _demo_results = [
        {
            "id": i + 1,
            "protocol_type": proto,
            "service": svc,
            "flag": flag,
            "src_bytes": nbytes,
            "classification": cls,
            "confidence": conf,
            "status": status,
        }
        for i, (proto, svc, flag, nbytes, cls, conf, status) in enumerate(
            [
                ("tcp", "http",     "SF",   215,  "Normal", 0.97, "ALLOWED"),
                ("tcp", "ftp_data", "SF",   491,  "Normal", 0.95, "ALLOWED"),
                ("icmp", "eco_i",   "SF",   0,    "Probe",  0.88, "BLOCKED"),
                ("tcp", "telnet",   "S0",   0,    "DoS",    0.93, "BLOCKED"),
                ("tcp", "smtp",     "SF",   2048, "R2L",    0.76, "BLOCKED"),
                ("udp", "private",  "SF",   105,  "Normal", 0.99, "ALLOWED"),
                ("tcp", "ftp",      "REJ",  0,    "U2R",    0.81, "BLOCKED"),
                ("tcp", "http",     "SF",   324,  "Normal", 0.96, "ALLOWED"),
            ]
        )
    ]

    _demo_stats = {
        "num_neurons": 21663,
        "num_synapses": 3457889,
        "accuracy": 0.9412,
        "f1_macro": 0.9187,
    }

    out = generate_security_report(_demo_results, _demo_stats)
    print(f"Report generated: {out}")
